# Generated by Django 3.2.16 on 2022-12-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Ресторан', 'verbose_name_plural': 'Ресторани'},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
    ]
